config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root 'messages#index'
  get 'rabin', to: 'messages#rabin'
  get 'crush', to: 'messages#crush'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  mount ActionCable.server => '/cable'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    enum status: { unread: 0, read: 1 }
    enum sender: { rabin: 0, crush: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  def rabin
    @messages = Message.all
    @message = Message.new
  end

  def crush
    @messages = Message.all
    @message = Message.new
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    if params[:message][:sender].present?
      params[:message][:sender] = params[:message][:sender].to_i
    end
    @message = Message.new(message_params)

    if @message.save
      ActionCable.server.broadcast 'message_channel', message: render_message(@message)
    end
    redirect_to request.referrer || root_url
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :status, :sender)
    end

    def render_message(message)
      MessagesController.renderer.render(partial: 'messages/message', locals: { message: message })
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rabinloveshiscrush
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    %link{:href => "https://fonts.googleapis.com", :rel => "preconnect"}/
    %link{:crossorigin => "", :href => "https://fonts.gstatic.com", :rel => "preconnect"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Playwrite+FR+Moderne:wght@100..400&display=swap", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_form.html.haml
= form_with(model: message) do |form|
  - if message.errors.any?
    #error_explanation
      %h2
        = pluralize(message.errors.count, "error")
        prohibited this message from being saved:
      %ul
        - message.errors.each do |error|
          %li= error.full_message
  .field
    = form.text_area :body, class: 'chatroom_form_inputbox'
  .field.hidden
    = form.label :sender
    = form.number_field :sender
  .actions
    = form.submit class: 'chatroom_form_sendBtn'

app/views/messages/_message.html.haml
%li.chatroom_history_list_item.chatroom_history_list_left{:class => message.sender}= message.body

app/views/messages/crush.html.haml
= link_to root_path do
  %h1 RabinLovesHisCrush

%p.logged Logged in as Rabin's Crush

.chatroom.crush-room
  .chatroom_section.chatroom_header
    .chatroom_section.chatroom_header_name Rabin
  .chatroom_section.chatroom_history
    %ul.chatroom_history_list
      - @messages.each do |message|
        = render 'message', message: message
  .chatroom_section.chatroom_form
    = render 'form', message: @message

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.haml
%p#notice= notice

.container
	%h1 RabinLovesHisCrush
	%p Log in as:
	.buttons
		= link_to 'Rabin', rabin_path, class: 'btn rabin button'
		= link_to "Rabin's Crush", crush_path, class: 'btn crush button'

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/rabin.html.haml
= link_to root_path do
  %h1 RabinLovesHisCrush

%p.logged Logged in as Rabin

.chatroom.rabin-room
  .chatroom_section.chatroom_header
    .chatroom_section.chatroom_header_name Crush
  .chatroom_section.chatroom_history
    %ul.chatroom_history_list
      - @messages.each do |message|
        = render 'message', message: message
  .chatroom_section.chatroom_form
    = render 'form', message: @message

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @message.status %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>